"""文件说明：推理模型、引擎开关和算子选项的默认值定义。"""

DEFAULT_INFERENCE_ENGINE_OPTIONS = [
    {
        "id": "trace_enabled",
        "name": "数据埋点",
        "description": "控制引擎阶段埋点与算子 profiling，关闭后更接近纯推理速度。",
        "default_enabled": False,
        "requires_restart": True,
    },
    {
        "id": "optimized_weight_loading",
        "name": "连续权重加载",
        "description": "启用连续 GPU 权重池和 bulk H2D 拷贝，减少模型冷启动时的大量碎片化 cudaMemcpy/cudaMalloc。",
        "default_enabled": False,
        "requires_restart": True,
    },
    {
        "id": "paged_kv_cache",
        "name": "分页 KV Cache",
        "description": "将 KV cache 改为按页懒分配，避免模型启动时一次性申请整块 max_seq_len KV 显存，加快冷启动。",
        "default_enabled": True,
        "requires_restart": True,
    },
    {
        "id": "warmup_on_model_switch",
        "name": "切模预热",
        "description": "切换模型后立即启动常驻进程，减少首条请求的冷启动等待。",
        "default_enabled": True,
        "requires_restart": False,
    },
]


DEFAULT_INFERENCE_OPERATOR_OPTIONS = [
    {
        "id": "matmul_impl",
        "name": "GEMM / MatMul",
        "description": "控制线性层主乘法算子的 CUDA 实现版本。",
        "env_var": "KLLM_OP_MATMUL_IMPL",
        "default_selected": "kuiper_cuda",
        "requires_restart": True,
        "choices": [
            {
                "id": "kuiper_cuda",
                "name": "Kuiper CUDA",
                "description": "项目当前默认 CUDA kernel，适合单 token decode 场景。",
                "supported": True,
            },
            {
                "id": "cublas",
                "name": "cuBLAS",
                "description": "基于 cuBLAS 的 GEMMEx 实现，bf16 权重会先将激活转换为 bf16 后再计算。",
                "supported": True,
            },
            {
                "id": "lab_cp_async_fp32",
                "name": "Lab cp.async Decode",
                "description": "基于手写 cp.async tile GEMM 思路改造的实验版实现，当前覆盖 fp32/bf16 权重的单 token decode matmul；不满足条件时会自动回退。",
                "supported": True,
            },
        ],
    },
    {
        "id": "rmsnorm_impl",
        "name": "RMSNorm",
        "description": "控制 RMSNorm 的 CUDA 实现版本。",
        "env_var": "KLLM_OP_RMSNORM_IMPL",
        "default_selected": "kuiper_cuda",
        "requires_restart": True,
        "choices": [
            {
                "id": "kuiper_cuda",
                "name": "Kuiper CUDA",
                "description": "项目当前默认 RMSNorm kernel。",
                "supported": True,
            },
            {
                "id": "lab_warp_reduce",
                "name": "Lab Warp Reduce",
                "description": "基于 warp reduce 的实验版 RMSNorm 实现。",
                "supported": True,
            },
        ],
    },
]


DEFAULT_INFERENCE_MODELS = [
    {
        "id": "qwen2_5_1_5b_instruct",
        "name": "Qwen2.5-1.5B-Instruct",
        "family": "qwen2",
        "model_dir": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen2.5-1.5B-Instruct",
        "model_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen2.5-1.5B-Instruct/Qwen2.5-1.5B-Instruct.bin",
        "tokenizer_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen2.5-1.5B-Instruct/tokenizer.json",
        "executable_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/build/demo/qwen_infer",
        "prompt_format": "chatml",
    },
    {
        "id": "qwen3_1_7b",
        "name": "Qwen3-1.7B",
        "family": "qwen3",
        "model_dir": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-1.7B",
        "model_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-1.7B/Qwen3-1.7B.bin",
        "tokenizer_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-1.7B/tokenizer.json",
        "executable_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/build/demo/qwen3_infer",
        "prompt_format": "chatml",
        "max_new_tokens": 256,
    },
    {
        "id": "qwen3_1_7b_bf16",
        "name": "Qwen3-1.7B-BF16",
        "family": "qwen3",
        "model_dir": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-1.7B",
        "model_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-1.7B/Qwen3-1.7B-bf16.bin",
        "tokenizer_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-1.7B/tokenizer.json",
        "executable_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/build/demo/qwen3_infer",
        "prompt_format": "chatml",
        "max_new_tokens": 256,
    },
    {
        "id": "qwen3_0_6b",
        "name": "Qwen3-0.6B",
        "family": "qwen3",
        "model_dir": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-0.6B",
        "model_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-0.6B/Qwen3-0.6B.bin",
        "tokenizer_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-0.6B/tokenizer.json",
        "executable_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/build/demo/qwen3_infer",
        "prompt_format": "chatml",
        "max_new_tokens": 256,
    },
    {
        "id": "qwen3_4b_thinking_2507_int8",
        "name": "Qwen3-4B-Thinking-2507-INT8",
        "family": "qwen3",
        "model_dir": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-4B-Thinking-2507",
        "model_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-4B-Thinking-2507/Qwen3-4B-Thinking-2507-int8.bin",
        "tokenizer_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-4B-Thinking-2507/tokenizer.json",
        "executable_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/build/demo/qwen3_infer",
        "prompt_format": "chatml",
        "supports_reasoning": True,
        "max_new_tokens": 8192,
    },
    {
        "id": "qwen3_4b_instruct_2507_int8",
        "name": "Qwen3-4B-Instruct-2507-INT8",
        "family": "qwen3",
        "model_dir": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-4B-Instruct-2507",
        "model_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-4B-Instruct-2507/Qwen3-4B-Instruct-2507-int8.bin",
        "tokenizer_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-4B-Instruct-2507/tokenizer.json",
        "executable_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/build/demo/qwen3_infer",
        "prompt_format": "chatml",
        "supports_reasoning": False,
        "max_new_tokens": 8192,
    },
    {
        "id": "qwen3_8b_awq_int4",
        "name": "Qwen3-8B-AWQ-INT4",
        "family": "qwen3",
        "model_dir": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-8B",
        "model_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-8B/Qwen3-8B-awq-int4.bin",
        "tokenizer_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen3-8B/tokenizer.json",
        "executable_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/build/demo/qwen3_infer",
        "prompt_format": "chatml",
        "supports_reasoning": True,
        "max_new_tokens": 8192,
    },
    {
        "id": "llama_3_2_1b_instruct_bf16",
        "name": "Llama-3.2-1B-Instruct-BF16",
        "family": "llama3",
        "model_dir": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Llama-3.2-1B-Instruct",
        "model_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Llama-3.2-1B-Instruct/Llama-3.2-1B-Instruct-bf16.bin",
        "tokenizer_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Llama-3.2-1B-Instruct/tokenizer.json",
        "executable_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/build/demo/llama3_infer",
        "prompt_format": "llama3",
        "max_new_tokens": 256,
    },
    {
        "id": "tinyllama_1_1b_chat_v1_0_bf16",
        "name": "TinyLlama-1.1B-Chat-v1.0-BF16",
        "family": "tinyllama",
        "model_dir": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/TinyLlama-1.1B-Chat-v1.0",
        "model_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/TinyLlama-1.1B-Chat-v1.0/TinyLlama-1.1B-Chat-v1.0-bf16.bin",
        "tokenizer_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/TinyLlama-1.1B-Chat-v1.0/tokenizer.model",
        "executable_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/build/demo/tinyllama_infer",
        "prompt_format": "tinyllama",
        "max_new_tokens": 256,
    },
    {
        "id": "smollm2_1_7b_instruct_bf16",
        "name": "SmolLM2-1.7B-Instruct-BF16",
        "family": "smollm",
        "model_dir": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/SmolLM2-1.7B-Instruct",
        "model_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/SmolLM2-1.7B-Instruct/SmolLM2-1.7B-Instruct-bf16.bin",
        "tokenizer_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/SmolLM2-1.7B-Instruct/tokenizer.json",
        "executable_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/build/demo/smollm_infer",
        "prompt_format": "chatml",
        "max_new_tokens": 256,
    },
    {
        "id": "deepseek_r1_distill_qwen_1_5b_bf16",
        "name": "DeepSeek-R1-Distill-Qwen-1.5B-BF16",
        "family": "deepseek_qwen",
        "model_dir": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/DeepSeek-R1-Distill-Qwen-1.5B",
        "model_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/DeepSeek-R1-Distill-Qwen-1.5B/DeepSeek-R1-Distill-Qwen-1.5B-bf16.bin",
        "tokenizer_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/DeepSeek-R1-Distill-Qwen-1.5B/tokenizer.json",
        "executable_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/demo/deepseek_qwen_infer.py",
        "prompt_format": "deepseek",
        "max_new_tokens": 256,
    },
    {
        "id": "qwen2_0_5b",
        "name": "Qwen2.5-0.5B",
        "family": "qwen2",
        "model_dir": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen2.5-0.5B",
        "model_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen2.5-0.5B/Qwen2.5-0.5B.bin",
        "tokenizer_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/models/Qwen2.5-0.5B/tokenizer.json",
        "executable_path": "/mnt/d/Project_Repository/Open_Source_Projects/MyInferenceEngine/KuiperLLama/build/demo/qwen_infer",
        "prompt_format": "chatml",
    },
]
